steps:
  # Step 0: Create a temporary workspace directory
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'mkdir -p /tmp/workspace'

  # Step 1: Clone the GitHub repository into the temporary workspace
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://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@github.com/bsuharik/melamenus', '/tmp/workspace']

  # Step 1.5: List contents of the workspace directory
  - name: 'gcr.io/cloud-builders/git'
    args: ['ls', '-l', '/tmp/workspace']

  # Step 2: Build the Docker image using files from the temporary workspace
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/stellar-state-376608/your-app', '/tmp/workspace']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/stellar-state-376608/your-app']

  # Step 4: SSH into the Compute Engine instance and pull the latest changes
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'weblaravel-vm'
      - '--zone=asia-southeast1-a'
      - '--command="cd /var/www/html && docker-compose pull && docker-compose up -d"'
    # Replace 'your-instance-zone' with your actual instance zone

images:
  - 'gcr.io/stellar-state-376608/your-app'