steps:
  # Step 1: Clone GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/bsuharik/melamenus', '/workspace']

  # Step 2: Replace directory on server
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ssh bryansuharik@weblaravel-vm 'rm -rf /var/www/html/*'
        scp -r /workspace/* bryansuharik@weblaravel-vm:/var/www/html
